disabled = false
locale = "es"
label = "Español"
weight = 1
title = "Congreso Anual de la Federación Andaluza de Fotografía 2026"

[params]
displayName = "ES"
isoCode = "es"
rtl = false
dateFormat = "2 Enero 2006"

["params.author"]
name = "Vera Zhurba Durglishvili"
email = "vera@espinacco.es"
